version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: project_dashboard
    volumes:
      - ./:/var/www
    ports:
      - "9007:9007" # Laravel PHP-FPM
    working_dir: /var/www
    env_file:
      - .env
    # networks:
    #   - email-builder_default
    command: sh -c "composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=9007"

  vite_dev:
    image: node:20
    container_name: vite_dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    env_file:
      - .env
    # networks:
    #   - email-builder_default

  db:
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "4833:5432"

volumes:
  db-data:

# networks:
#   email-builder_default:
#     external: true