version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: project_dashboard
    volumes:
      - ./:/var/www
    ports:
      - "9007:9007"   # Laravel PHP-FPM
    working_dir: /var/www
    env_file:
      - .env
    networks:
      - email-builder_default
    command: php artisan serve --host=0.0.0.0 --port=9007

  vite_dev:
    image: node:20
    container_name: vite_dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    env_file:
      - .env
    networks:
      - email-builder_default

networks:
  email-builder_default:
    external: true
